package com.app.mydaybook.common.enums.exception;


public enum ErrorCode {
    HABIT_NOT_FOUND,
    HABIT_ALREADY_EXISTS,
    HABIT_NAME_REQUIRED,
    HABIT_START_DATE_REQUIRED,
    HABIT_END_DATE_REQUIRED,
    HABIT_CATEGORY_OBLIGATORY,
    TASK_NOT_FOUND,
    TASK_ALREADY_EXISTS,
    TASK_NAME_REQUIRED,
    CATEGORY_NOT_FOUND,
    CATEGORY_ALREADY_EXISTS,
    CATEGORY_NAME_REQUIRED,
    END_DATE_BEFORE_START_DATE;
}
